#!/usr/bin/python3

import sys
import json
import argparse
import pprint
from bson import ObjectId
import utils
#----------------------------------------------------------------------------------------------------------------------------------

def parse_args(args):
    """ Parse the arguments.
    """
    parser = argparse.ArgumentParser(prog='tokengen', description='Eyeflow Create Environment')
    parser.add_argument('edge_id', help='The ID of edge device', type=str)
    parser.add_argument('environment_id', help='The ID of client environment', type=str)
    parser.add_argument('--out_file', '-o', dest='out_file', help='The json file to save device info', type=str, action='store', default='license.json')

    return parser.parse_args(args)
#----------------------------------------------------------------------------------------------------------------------------------

def main(args=None):
    # parse arguments
    if args is None:
        args = sys.argv[1:]

    args = parse_args(args)

    device_info = utils.get_device_info()

    try:
        ObjectId(args.edge_id)
    except:
        print("ERROR: edge-id is not a valid ID")
        exit(1)

    try:
        ObjectId(args.environment_id)
    except:
        print("ERROR: environment-id is not a valid ID")
        exit(1)

    device_info["edge_id"] = args.edge_id
    device_info["environment_id"] = args.environment_id

    with open(args.out_file, 'w') as fp:
        json.dump(device_info, fp, default=str, ensure_ascii=False)

    pprint.pprint(device_info)
#----------------------------------------------------------------------------------------------------------------------------------

main()
